version: '3.7'
services:
  server:
    container_name: ancillary-recon
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000      
