version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python ./validate.py boyd-invoice.xlsx
    command: tail -f /dev/null
    volumes:
      - .:/app
