version: '3.7'
services:
  server:
    environment: 
      - "bucket=ancillary-reconciliation"
      - "db_host="
      - "db_name="
      - "db_user="
      - "db_password="
      - "QUEUE_NAME=ltc-ancillary-reconciliation.fifo"
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
